# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('created_dt', models.DateTimeField(auto_now=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('forall', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='points',
            unique_together=set([('longitude', 'latitude', 'altitude')]),
        ),
    ]
