# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mld', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Points',
            new_name='Targets',
        ),
    ]
